# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New Manor Farm Shop
email: chris@chrisbarnes.co
description: > # this means to ignore newlines until "baseurl:"
  New Manor Farm Shop
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://newmanorfarmshop.co.uk/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

# sass settings
sass:
    sass_dir: _sass
    style: compressed
    
plugins:
  - jekyll-sitemap

